#cloud-config

groups:
  - k8s-admin

users:
${users}

write_files:
  - path: /etc/default/yakity
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${yakity_env}

runcmd:
  - mkdir -p /opt/bin
  - curl -sSL -o /opt/bin/yakity.sh ${yakity_url}
  - chmod 0755 /opt/bin/yakity.sh
  - /opt/bin/yakity.sh ${node_type} 2>&1 | tee /var/log/yakity.log
