#cloud-config

groups:
  - k8s-admin

users:
${users}

write_files:
  - path: /etc/default/yakity
    owner: root:root
    permissions: 0644
    encoding: gzip
    content: !!binary |
      ${yakity_env}

  - path: /opt/bin/yakity.sh
    owner: root:root
    permissions: 0755
    encoding: gzip
    content: !!binary |
      ${yakity_sh}

runcmd:
  - /opt/bin/yakity.sh ${node_type}
